name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: ["**"]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22 (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Biome CI
        run: npm run ci:biome
 